# Generated by Django 4.2.12 on 2025-01-20 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoF', '0008_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
