name: Snyk

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  snyk-scan:
    runs-on: ubuntu-latest

    steps:
      # Configura el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Configura Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Instala las dependencias del proyecto
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # Instala Node.js (necesario para Snyk CLI)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Puedes usar la versión que prefieras

      # Instala Snyk CLI con npm
      - name: Install Snyk
        run: npm install -g snyk

      # Autentica con Snyk
      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      # Escanea las dependencias del proyecto
      - name: Run Snyk Test
        run: snyk test --skip-unresolved

      # (Opcional) Monitorea el proyecto en Snyk
      - name: Monitor Snyk Project
        run: snyk monitor --skip-unresolved
