name: OWASP ZAP DAST Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  owasp-zap:
    runs-on: ubuntu-latest

    services:
      zap:
        image: owasp/zap2docker-stable
        options: --privileged --network host

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Start ZAP
        run: |
          docker pull owasp/zap2docker-stable
          docker run -d -p 8080:8080 owasp/zap2docker-stable zap-api-scan.py -t https://github.com/AntonioCartuche/ApplyingDevOps.git/zap-scan-target-url

      - name: Run OWASP ZAP API Scan
        env:
          ZAP_API_KEY: ${{ secrets.ZAP_API_KEY }}
        run: |
          docker run -t owasp/zap2docker-stable zap-api-scan.py -t https://github.com/AntonioCartuche/ApplyingDevOps.git/zap-scan-target-url -f openapi -J -H zap_proxy:8080
