name: DAST

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  owasp-zap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install OWASP ZAP
        run: |
          # Añadir el repositorio de ZAP y sus claves
          sudo apt-get update
          sudo apt-get install -y gnupg curl lsb-release
          curl -fsSL https://archive.zaproxy.org/debian/zed-archive.key | sudo tee /etc/apt/trusted.gpg.d/zed-archive.asc
          echo "deb https://archive.zaproxy.org/debian/ $(lsb_release -c | awk '{print $2}') main" | sudo tee /etc/apt/sources.list.d/owasp-zap.list
          
          # Instalar ZAP
          sudo apt-get update
          sudo apt-get install -y zaproxy

      - name: Start ZAP
        run: |
          zap.sh -daemon -port 8080 -config api.key=${{ secrets.ZAP_API_KEY }}

      - name: Run OWASP ZAP API Scan
        env:
          ZAP_API_KEY: ${{ secrets.ZAP_API_KEY }}
        run: |
          curl -LO https://raw.githubusercontent.com/stevescargall/zap-scan/master/zap-api-scan.py
          python3 zap-api-scan.py -t https://github.com/AntonioCartuche/ApplyingDevOps.git/zap-scan-target-url -f openapi -J -H http://localhost:8080
