name: Build and Test

on:
  push:
    branches:
      - main  # Activará el flujo de trabajo cuando se haga un push a la rama principal
  pull_request:
    branches:
      - main  # También se ejecutará cuando se abra un pull request hacia la rama principal

jobs:
  build:
    runs-on: ubuntu-latest  # Define el sistema operativo donde se ejecutará el trabajo

    steps:
    - name: Check out code
      uses: actions/checkout@v3  # Esto descarga el código del repositorio

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Configura la versión de Python para el proyecto

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Instala las dependencias del proyecto

    - name: Run tests
      run: |
        pytest  # Ejecuta las pruebas con pytest
