name: License Compliance Check

on:
  push:
    branches:
      - main
      - 'release/*'
      - master
  pull_request:

jobs:
  license-check:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Configurar entorno para Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Instalar dependencias
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pip-licenses

      # 4. Generar archivo de licencias
      - name: Generate License Report
        run: pip-licenses --format=json --output-file=license-results.txt

      # 5. License compliance check
      - name: License Compliance Check
        uses: mikaelvesavuori/license-compliance-action@v1
        with:
          allow_licenses: "MIT;ISC;0BSD;BSD-2-Clause;BSD-3-Clause;Apache-2.0;GPL-3.0;LGPL-3.0"
          nested_field: "licenseString"

      # 6. Verifica si el archivo se generó
      - name: Check License Results
        run: cat ./license-results.txt || echo "No license results found."

      # 7. Subir el artefacto (si existe)
      - name: Upload License Results
        uses: actions/upload-artifact@v3
        with:
          name: license-results
          path: ./license-results.txt
