name: License Compliance Check

on:
  push:
    branches:
      - main
      - "release/*"
      - master
  pull_request:

jobs:
  license-check:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Obtener el repositorio
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Paso 2: Validar licencias permitidas
      - name: License Compliance Check
        uses: mikaelvesavuori/license-compliance-action@v1
        with:
          allow_licenses: "MIT;ISC;0BSD;BSD-2-Clause;BSD-3-Clause;Apache-2.0;GPL-3.0;LGPL-3.0"
          nested_field: "licenseString"

      # Paso 3: Generar un reporte (opcional, para hacerlo más interesante)
      - name: Generate License Report
        if: failure()
        run: |
          echo "Una o más licencias no permitidas fueron detectadas."
          echo "Revise las dependencias del proyecto y asegúrese de utilizar solo las licencias aceptadas."

      # Paso 4: Publicar resultados (opcional)
      - name: Upload License Compliance Results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: license-compliance-results
          path: ./license-results.txt # Este archivo se genera si hay un reporte adicional
